import * as FileSystem from 'expo-file-system';

const STORAGE_THEME_KEY = "APP_THEME";
const STORAGE_BUDGET_KEY = "APP_BUDGET";
const STORAGE_PROVISION_KEY = "APP_PROVISION";
const STORAGE_NOTIFICATION_KEY = "APP_NOTIFICATION";
const STORAGE_DEPENSES_KEY = "APP_DEPENSES";
const STORAGE_USER_KEY = "APP_USER";
const STORAGE_PASSWORD_KEY = "APP_PASSWORD";
const STORAGE_GOAL_KEY = "APP_GOAL";
const STORAGE_HOUR_NOTIFICATION_KEY = "APP_HOUR_NOTIFICATION";
const SCHEDULE_LOCK_KEY = "notif_schedule_lock";
const ENABLE_KEY = "notification_enabled";
const DAILY_KEY = "daily_notification_id";
const LAST_EXPENSE_DATE_KEY = "last_expense_date";
const CURRENT_SEARCH_KEY = "CURRENT_SEARCH";
const MESSAGE_KEY = "message";
const DOSSIER_AUDIOS = `${FileSystem.documentDirectory}audios/`;
const DOSSIER_IMAGES = `${FileSystem.documentDirectory}images/`;
const STORAGE_TODO_KEY = "todos";
const STORAGE_LISTE_COURSE_KEY = "liste_courses";
const STORAGE_PROVISION_CONSOMMATION_KEY = "provision_consommations";

const LAST_CHECK_KEY = (goalId: string) => `goal_last_check_${goalId}`;
const NOTIFICATION_APP_KEY = (userId: string) => `notifications_${userId}`;

export {
  STORAGE_THEME_KEY,
  STORAGE_BUDGET_KEY,
  STORAGE_PROVISION_KEY,
  STORAGE_NOTIFICATION_KEY,
  STORAGE_DEPENSES_KEY,
  STORAGE_USER_KEY,
  STORAGE_PASSWORD_KEY,
  STORAGE_GOAL_KEY,
  STORAGE_HOUR_NOTIFICATION_KEY,
  SCHEDULE_LOCK_KEY,
  ENABLE_KEY,
  DAILY_KEY,
  LAST_EXPENSE_DATE_KEY,
  CURRENT_SEARCH_KEY,
  MESSAGE_KEY,
  DOSSIER_AUDIOS,
  DOSSIER_IMAGES,
  STORAGE_TODO_KEY,
  STORAGE_LISTE_COURSE_KEY,
  STORAGE_PROVISION_CONSOMMATION_KEY,

  LAST_CHECK_KEY,
  NOTIFICATION_APP_KEY,
};