const STORAGE_THEME_KEY = "APP_THEME";
const STORAGE_BUDGET_KEY = "APP_BUDGET";
const STORAGE_PROVISION_KEY = "APP_PROVISION";
const STORAGE_NOTIFICATION_KEY = "APP_NOTIFICATION";
const STORAGE_DEPENSES_KEY = "APP_DEPENSES";
const STORAGE_USER_KEY = "APP_USER";
const STORAGE_PASSWORD_KEY = "APP_PASSWORD";
const STORAGE_GOAL_KEY = "APP_GOAL";

export {
  STORAGE_THEME_KEY,
  STORAGE_BUDGET_KEY,
  STORAGE_PROVISION_KEY,
  STORAGE_NOTIFICATION_KEY,
  STORAGE_DEPENSES_KEY,
  STORAGE_USER_KEY,
  STORAGE_PASSWORD_KEY,
  STORAGE_GOAL_KEY,
};